apiVersion: v2
name: linsoft-demo
description: Microservice FastAPI déployé sur Kubernetes
type: application
version: 0.1.0        # version du chart lui-même
appVersion: "1.0.0"   # version de ton application